# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

@typing.final
class EstimateError:
    r"""
    Parameters for estimating the error of the analysis.
    
    Parameters
    ----------
    n_blocks : int, default=5
        Number of blocks to divide the trajectory for error estimation.
        Must be at least 2. It is recommended not to modify this value to
        artificially reduce error estimates.
    output_convergence : Optional[str], default=None
        Filename for writing convergence data. If omitted, convergence analysis
        is still performed but results are not written into a file.
    
    Raises
    ------
    ConfigError
        If `n_blocks` is less than 2.
    """
    def __new__(cls, n_blocks: builtins.int = 5, output_convergence: typing.Optional[builtins.str] = None) -> EstimateError: ...

