# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import numpy
import typing
import gorder
import gorder
import gorder

@typing.final
class ClusteringClassification:
    r"""
    Assign lipids into leaflets using spectral clustering.
    
    Reliable but very slow. Recommended for curved membranes, tubes and vesicles.
    
    Parameters
    ----------
    heads : str
        Selection query specifying reference atoms representing lipid headgroups
        (typically phosphorus atoms or phosphate beads).
        There must be exactly one such atom/bead per lipid molecule.
    frequency : Optional[Frequency]
        Frequency of classification. Defaults to every frame.
    collect : Optional[Union[bool, str]], default=False
        Determines whether leaflet classification data are saved and exported.
        By default (`False`), data are not saved.
        If `True`, data are saved internally and accessible via the Python API, but not written to a file.
        If a string is provided, data are saved and written to the specified output file.
    flip : bool, default=False
        Flip the assignment. Upper leaflet becomes lower leaflet and vice versa. The default value is False.
    """
    def __new__(cls, heads: builtins.str, frequency: typing.Optional[gorder.Frequency] = None, collect: typing.Optional[typing.Union[builtins.bool, builtins.str]] = None, flip: builtins.bool = False) -> ClusteringClassification: ...

@typing.final
class GlobalClassification:
    r"""
    Assign lipids into leaflets based on the global membrane center of geometry.
    
    Reliable for planar membranes and fast. Recommended for most membranes.
    
    Parameters
    ----------
    membrane : str
        Selection query specifying all lipids forming the membrane.
    heads : str
        Selection query specifying reference atoms representing lipid headgroups
        (typically phosphorus atoms or phosphate beads).
        There must be exactly one such atom/bead per lipid molecule.
    frequency : Optional[Frequency]
        Frequency of classification. Defaults to every frame.
    membrane_normal : Optional[str]
        Membrane normal used for leaflet classification. Defaults to the membrane normal
        specified for the entire Analysis.
    collect : Optional[Union[bool, str]], default=False
        Determines whether leaflet classification data are saved and exported.
        By default (`False`), data are not saved.
        If `True`, data are saved internally and accessible via the Python API, but not written to a file.
        If a string is provided, data are saved and written to the specified output file.
    flip : bool, default=False
        Flip the assignment. Upper leaflet becomes lower leaflet and vice versa. The default value is False.
    """
    def __new__(cls, membrane: builtins.str, heads: builtins.str, frequency: typing.Optional[gorder.Frequency] = None, membrane_normal: typing.Optional[builtins.str] = None, collect: typing.Optional[typing.Union[builtins.bool, builtins.str]] = None, flip: builtins.bool = False) -> GlobalClassification: ...

@typing.final
class IndividualClassification:
    r"""
    Assign lipids into leaflets based on the orientation of acyl chains.
    
    Less reliable but very fast. Recommended for very large, undulating planar membranes.
    
    Parameters
    ----------
    heads : str
        Selection query specifying reference atoms representing lipid headgroups
        (typically phosphorus atoms or phosphate beads).
        There must be exactly one such atom/bead per lipid molecule.
    methyls : str
        Selection query specifying reference atoms representing methyl groups at the ends of lipid tails.
        There should be exactly one such atom/bead per acyl chain (e.g., two for lipids with two acyl chains).
    frequency : Optional[Frequency]
        Frequency of classification. Defaults to every frame.
    membrane_normal : Optional[str]
        Membrane normal used for leaflet classification. Defaults to the membrane normal
        specified for the entire Analysis.
    collect : Optional[Union[bool, str]], default=False
        Determines whether leaflet classification data are saved and exported.
        By default (`False`), data are not saved.
        If `True`, data are saved internally and accessible via the Python API, but not written to a file.
        If a string is provided, data are saved and written to the specified output file.
    flip : bool, default=False
        Flip the assignment. Upper leaflet becomes lower leaflet and vice versa. The default value is False.
    """
    def __new__(cls, heads: builtins.str, methyls: builtins.str, frequency: typing.Optional[gorder.Frequency] = None, membrane_normal: typing.Optional[builtins.str] = None, collect: typing.Optional[typing.Union[builtins.bool, builtins.str]] = None, flip: builtins.bool = False) -> IndividualClassification: ...

@typing.final
class LocalClassification:
    r"""
    Assign lipids into leaflets based on the local membrane center of geometry.
    
    Reliable for planar membranes but slow.
    Recommended for planar membranes if the global and individual methods do not work for you.
    
    Parameters
    ----------
    membrane : str
        Selection query specifying all lipids forming the membrane.
    heads : str
        Selection query specifying reference atoms representing lipid headgroups
        (typically phosphorus atoms or phosphate beads).
        There must be exactly one such atom/bead per lipid molecule.
    radius : float
        Radius of a cylinder used to calculate the local membrane center of geometry (in nm).
    frequency : Optional[Frequency]
        Frequency of classification. Defaults to every frame.
    membrane_normal : Optional[str]
        Membrane normal used for leaflet classification. Defaults to the membrane normal
        specified for the entire Analysis.
    collect : Optional[Union[bool, str]], default=False
        Determines whether leaflet classification data are saved and exported.
        By default (`False`), data are not saved.
        If `True`, data are saved internally and accessible via the Python API, but not written to a file.
        If a string is provided, data are saved and written to the specified output file.
    flip : bool, default=False
        Flip the assignment. Upper leaflet becomes lower leaflet and vice versa. The default value is False.
    """
    def __new__(cls, membrane: builtins.str, heads: builtins.str, radius: builtins.float, frequency: typing.Optional[gorder.Frequency] = None, membrane_normal: typing.Optional[builtins.str] = None, collect: typing.Optional[typing.Union[builtins.bool, builtins.str]] = None, flip: builtins.bool = False) -> LocalClassification: ...

@typing.final
class ManualClassification:
    r"""
    Get leaflet assignment from an external YAML file or a dictionary.
    
    Parameters
    ----------
    input : Union[str, Mapping[str, ndarray[uint8]]]
        Path to the input YAML file containing the leaflet assignment
        or a dictionary specifying the leaflet assignment.
    frequency : Optional[Frequency]
        Frequency of classification. Defaults to every frame.
    flip : bool, default=False
        Flip the assignment. Upper leaflet becomes lower leaflet and vice versa. The default value is False.
    """
    def __new__(cls, input: typing.Union[builtins.str, typing.Mapping[builtins.str, numpy.typing.NDArray[numpy.uint8]]], frequency: typing.Optional[gorder.Frequency] = None, flip: builtins.bool = False) -> ManualClassification: ...

@typing.final
class NdxClassification:
    r"""
    Get leaflet assignment from NDX file(s).
    
    Parameters
    ----------
    ndx : Sequence[str]
        A list of NDX files to read.
    heads : str
        Selection query specifying reference atoms representing lipid headgroups
        (typically phosphorus atoms or phosphate beads).
        There must be exactly one such atom/bead per lipid molecule.
    upper_leaflet : str
        Name of the group in the NDX file(s) specifying the atoms of the upper leaflet.
    lower_leaflet : str
        Name of the group in the NDX file(s) specifying the atoms of the lower leaflet.
    frequency : Optional[Frequency]
        Frequency of classification. Defaults to every frame.
    flip : bool, default=False
        Flip the assignment. Upper leaflet becomes lower leaflet and vice versa. The default value is False.
    
    Notes
    -----
    - No glob expansion is performed for the NDX files.
    """
    def __new__(cls, ndx: typing.Sequence[builtins.str], heads: builtins.str, upper_leaflet: builtins.str, lower_leaflet: builtins.str, frequency: typing.Optional[gorder.Frequency] = None, flip: builtins.bool = False) -> NdxClassification: ...

@typing.final
class SphericalClusteringClassification:
    r"""
    Assign lipids into leaflets using gaussian mixture model.
    
    Reliable for spherical vesicles and fast. Do not use for anything other than vesicles!
    
    Parameters
    ----------
    heads : str
        Selection query specifying reference atoms representing lipid headgroups
        (typically phosphorus atoms or phosphate beads).
        There must be exactly one such atom/bead per lipid molecule.
    frequency : Optional[Frequency]
        Frequency of classification. Defaults to every frame.
    collect : Optional[Union[bool, str]], default=False
        Determines whether leaflet classification data are saved and exported.
        By default (`False`), data are not saved.
        If `True`, data are saved internally and accessible via the Python API, but not written to a file.
        If a string is provided, data are saved and written to the specified output file.
    flip : bool, default=False
        Flip the assignment. Upper leaflet becomes lower leaflet and vice versa. The default value is False.
    """
    def __new__(cls, heads: builtins.str, frequency: typing.Optional[gorder.Frequency] = None, collect: typing.Optional[typing.Union[builtins.bool, builtins.str]] = None, flip: builtins.bool = False) -> SphericalClusteringClassification: ...

