# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

@typing.final
class DynamicNormal:
    r"""
    Request a dynamic local membrane normal calculation.
    
    Parameters
    ----------
    heads : str
        Selection query specifying reference atoms representing lipid headgroups
        (typically phosphorus atoms or phosphate beads). Must be exactly one
        atom/bead per lipid molecule.
    radius : float
        Radius of the sphere used to select nearby lipids for membrane normal
        estimation in nm. Recommended value is half the membrane thickness.
        Must be greater than 0. The default value is 2.0 (nm).
    collect : Optional[Union[bool, str]], default=False
        Determines whether dynamic membrane normals are saved and exported.
        By default (`False`), normals are not saved.
        If `True`, normals are saved internally and accessible via the Python API, but not written to a file.
        If a string is provided, normals are saved and written to the specified output file.
    
    Raises
    ------
    ConfigError
        If `radius` is not positive.
    """
    def __new__(cls, heads: builtins.str, radius: builtins.float = 2.0, collect: typing.Optional[typing.Union[builtins.bool, builtins.str]] = None) -> DynamicNormal: ...

